#pragma once

#include "NativeGameplayTags.h"

namespace PFGameplayTags
{
	// 공격 어빌리티 태그
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Ability_Attack);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Ability_Attack_Kwang);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Ability_Attack_Twinblast_NormalAttack);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Ability_Attack_Twinblast_UltAttack);

	// 캐릭터 상태 태그
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Attacking);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Invulnerable);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Dead);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Ultimate);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Jumping);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Falling);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Sprinting);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_State_Attack_ComboWindow);
	// 아이템 쿨타임 태그
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Cooldown_HP);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Cooldown_MP);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Cooldown_Shield);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Item_Cooldown_Coin);
	// 공격 차단 태그
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Block_Attack);

	// 공격 타이밍 이벤트
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Event_Attack_ComboWindow);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Event_Attack_ComboReset);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(Character_Event_Attack_Shoot);

	// 아이템 연출 Cue 태그
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Item_Use_HP);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Item_Use_MP);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Item_Use_Shield);
	PORTFOLIO_API UE_DECLARE_GAMEPLAY_TAG_EXTERN(GameplayCue_Item_Use_Coin);
}
